enum ChanelEnum {
  CONNECT = 'CONNECT',
  ROOM = 'ROOM',
  USER_ONLINE = 'USER_ONLINE',
  ROOM_ONLINES = 'ROOM_ONLINES',
  MY_ROOMS = 'MY_ROOMS',
  NEW_INBOX = 'NEW_INBOX',
  NEW_INBOX_BY_ROOM = 'NEW_INBOX_BY_ROOM',
  JOIN_CALL = 'JOIN_CALL',
  CALLING = 'CALLING',
  WAITING_CALLING = 'WAITING_CALLING',
  UPDATING_INBOX = 'UPDATING_INBOX'
}

export default ChanelEnum
