enum ChanelEnum {
  CONNECT = 'CONNECT',
  ROOM = 'ROOM',
  USER_ONLINE = 'USER_ONLINE',
  ROOM_ONLINES = 'ROOM_ONLINES',
  MY_ROOMS = 'MY_ROOMS',
  NEW_INBOX = 'NEW_INBOX',
  NEW_INBOX_BY_ROOM = 'NEW_INBOX_BY_ROOM'
}

export default ChanelEnum
